
import Footer from "@/components/shared/Footer/Footer";
import "../styles/globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";



export const metadata = {
  title: "Frequency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
